version: "3"
services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    ports: 
      - 4000:5432
    env_file:
      - .env
    volumes:
      - pg_volume:/var/lib/postgresql/data
  
  node_app:
      container_name: node_app
      build: .
      ports: 
        - 5009:5000
      depends_on:
        - db
      env_file:
        - .env
volumes:
  pg_volume: